### ISSUE TITLE
importing as a package

### ISSUE THREAD

**Issue by manishiitg** [cryptagon/ion-cluster#16]
hi @billylindeman sorry to take your time again :)

is it possible to import ion-cluster as a go module?

i tried doing it but your module name https://github.com/cryptagon/ion-cluster/blob/master/go.mod#L1   `
module github.com/pion/ion-cluster<br class="Apple-interchange-newline">
`

and git url are different. so go gives any error?

or am i doing something wrong?

thanks

**Comment by billylindeman** [comment]
hm yeah that's because we intended on moving this to pion org eventually... 

why are you trying to import it as module, it's meant to be a standalone service

**Comment by manishiitg** [comment]
i mainly wanted to reused the gst producer package in ion load test, for now i have simply copy pasted the required files.
